install ack
install android-sdk
install apple-gcc42
install brew-cask
install closure-compiler
install couchdb
install ctags
install editorconfig
install elasticsearch
install ettercap
install faac
install ghostscript
install git
install git-flow
install gmp
install gnu-typist
install help2man
install htop-osx
install httpie
install imagemagick
install irssi
install jpegoptim
install lame
install leiningen
install libksba
install libvpx
install libxslt
install libyaml
install lynx
install macvim
install md5sha1sum
install mercurial
install mobile-shell
install mongodb
install mutt
install mysql
install optipng
install phantomjs
install python
install reattach-to-user-namespace
install redis
install ruby-build
install serialosc
install texi2html
install the_silver_searcher
install tmux
install tree
install vim
install x264
install xvid
install zlib
install zsh
