#! /usr/bin/env zsh

#
#
# Require Homebrew
# Requires zsh to install
#

mkdir -p ~/.vim/autoload ./bundle ~/.vim/tmp

git submodule init
git submodule update --recursive

ln -s ~/.env/bundle ~/.vim/bundle

# .vimrc
ln -s ~/.env/vimrc ~/.vimrc

# source to init.sh from .zshrc
# check first the presence of the line in .zshrc
# append the line if not available

source ~/.env/init.sh

./vms/nvm/install.sh
source ./vms/nvm/nvm.sh

nvm install 0.8
nvm use 0.8
nvm alias default 0.8

brew update

# Tools

#jshint
ln -s ~/.env/jshintrc ~/.jshintrc
npm install -g jshint

cd ~/.env/tools/doctorjs
git submodule update --init --recursive
sudo make install

brew install python
pip install --user git+git://github.com/Lokaltog/powerline

echo "You need to set up some path for the python executable... See the logs above"



# Powerline

take ~/.config
ln -s ~/.env/config/* .


# Disable spotlight
sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist

# The silver searcher (ag)
brew install the_silver_searcher

#vimpager
mkdir -p ~/bin
cd ~/bin
git clone git@github.com:rkitover/vimpager.git



ln -s ~/.env/vim/config ~/.vim/config
ln -s ~/.env/config/base16-shell ~/.config/base16-shell
brew install tree

gem install bundler

defaults write -g ApplePressAndHoldEnabled -bool false

# Disable local time machine backups
sudo tmutil disablelocal

brew install fzf
$(brew info fzf | grep /install)

# Trouble with C-h in Neovim+Tmux+iTerm?
# => https://github.com/neovim/neovim/issues/2048#issuecomment-78045837
