#! /usr/bin/env zsh

#
#
# Requires zsh + oh-my-zsh to install
# 
#

mkdir -p ~/.vim/autoload ./bundle

git submodule init 
git submodule update --recursive

ln -s ~/.env/bundle ~/.vim/bundle

# .vimrc
ln -s ~/.env/vimrc ~/.vimrc

# source to init.sh from .zshrc
# check first the presence of the line in .zshrc
# append the line if not available

source ~/.env/init.sh

./vms/nvm/install.sh
source ./vms/nvm/nvm.sh

nvm install 0.8
nvm use 0.8
nvm alias default 0.8

#Check the configure options to istall elsewhere that ~/.rvm
bash ~/.env/vms/rvm/binscripts/rvm-installer stable --ruby

# Tools

#jshint
ln -s ~/.env/jshintrc ~/.jshintrc
npm install -g jshint

cd ~/.env/tools/doctorjs
sudo make install
