#! /usr/bin/env sh

#
#
# Requires zsh + oh-my-zsh to install
# 
#

mkdir -p ~/.vim/autoload ./bundle

git submodule init
git submodule update

ln -s ~/.dotfiles/bundle ~/.vim/bundle

# .vimrc
ln -s ~/.dotfiles/vimrc ~/.vimrc

# source to init.sh from .zshrc
# check first the presence of the line in .zshrc
# append the line if not available
